# Form implementation generated from reading ui file 'resources/ui/add_user.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from multiprocessing import Queue
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog: QtWidgets.QDialog, q: Queue):
        self.q = q
        self.Dialog = Dialog
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(399, 211)
        qss = ''
        with open('resources/qss/add_user.qss', 'r', encoding='utf8') as f:
            for line in f:
                qss += line
        self.Dialog.setStyleSheet(qss)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 170, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(self.Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 69, 281, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 120, 281, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(self.Dialog)
        self.buttonBox.accepted.connect(self.do_add_user) # type: ignore
        self.buttonBox.rejected.connect(self.Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.Dialog.setWindowTitle(_translate("self.Dialog", "添加用户"))
        self.label.setText(_translate("self.Dialog", "id"))
        self.label_2.setText(_translate("self.Dialog", "账号"))
        self.label_3.setText(_translate("self.Dialog", "密码"))

    def do_add_user(self):
        if len(self.lineEdit.text()) > 0 and len(self.lineEdit_2.text()) > 0 and len(self.lineEdit_3.text()) > 0 and not self.q.full():
            self.q.put([1, self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text()])
            self.Dialog.accept()
        else:
            QtWidgets.QMessageBox.warning(self.Dialog, '警告', '请填写完整信息')